### ISSUE TITLE
Shields causing immense lag

### ISSUE THREAD

**Issue by LuxArdens** [rimworld-frontierdevelopment/Shields#101]
Noticed my base got enormously slow and stuttered (despite small size), and starting removing things. Got it nailed down to the 16 shields I was using. Disabling them immediately resolved the slowdown. No exceptions were thrown in the log. Even having just 2 shields up noticeable decreased performance. Having more makes the game borderline unplayable. No enemies on the map. Infinite energy doesn't fix it.

Would love to know if this is a known bug or something that can be fixed on my end. Absolutely love the mod, but effectively can't play with it right now :(

**Comment by JonnyNova** [comment]
Shields only have two functions when idle, consume power and generate heat. The actual blocking of projectiles is handled in the projectile code. Do you have other mods affecting either power or heat? This is probably a mod interaction conflict. Something like Turn it on and off would be one that comes to mind.

Though, a HugsLib log is really needed to track down what this is.

**Comment by LuxArdens** [comment]
Yeah, I think it's a conflict with Sladki's Idle Power Consumption. Will do a test later on to confirm.

**Comment by LuxArdens** [comment]
Confirmed. Sladki's Idle Power Consumption interferes with this mod. It doesn't throw any exceptions and both mods technically still work, but it uses up multiple tenths of seconds of CPU usage _per shield_. Requesting an update to the mod description to reflect incompatibility ;)

**Comment by JonnyNova** [comment]
I looked into it and it the issue is from Idle Power Consumption trying to change the behavior of the shields in a hacky way. There isn't anything that can be done from my side to support it. Support will need to be added on the other side.
