### ISSUE TITLE
Update to 1.1

### ISSUE THREAD

**Issue by JonnyNova** [rimworld-frontierdevelopment/Shields#102]
- [x] Compile for 1.1
- [ ] Add logging if a patch hunk fails to find patches that did not error but did not apply

Not working:
- [ ] Blocking projectiles

Needs Testing:
- [ ] Skyfallers

Tested working:
- [x] Block explosions
- [x] Verb
- [x] Cast position finder

Transpilers needing update:
- [ ] Projectile.Tick
- [ ] Bombardment.StartRandomFire

**Comment by BlkPingu** [comment]
Is this in progress? There hasn't a commit since almost a month ago. Love your work btw @JonnyNova

**Comment by simplyWiri** [comment]
Might not be the most elegant solution for the bombardment transpiler :)
~ In short, I look for the function which determines where an IntVec3 is valid (current check is .InBounds() ), and prefix it. Unfortunately it is an internal function, so the locating of the function is janky.
```
            var method = AccessTools.FirstMethod(typeof(Bombardment),
                inner => inner.Name.StartsWith("<StartRandomFire>") 
                && inner.ReturnType == typeof(bool));

            harmony.Patch(method, new HarmonyMethod(typeof(Harmony_Bombardment), nameof(Harmony_Bombardment.Prefix)));


        public static bool Prefix(Bombardment __instance, IntVec3 x, ref bool __result)
        {
            if (IsShielded(__instance.Map, x))
            {
                __result = false;
                return false;
            }
            return true;
        }
```

Please let me know if I can be of any more help, i'll look into the other transpiler at some point.

Cheers for the great mod

**Comment by JonnyNova** [comment]
Superceded by update to 1.2 in 5605e7ac7b28fba1348ac55c12338374997b6119
