### ISSUE TITLE
Shield generators affected by explosions not in shield range

### ISSUE THREAD

**Issue by techno156** [rimworld-frontierdevelopment/Shields#129]
If there is an explosion in the map, irrespective of whether it is in range of the shields, shield generators behave as though the shield has been impacted.

Recreation Steps:

1.  Place active shield.

1. Spawn many explosions using developer mode.

Shields will go heat up/go offline, even if the explosions are out of range of the shield radius, as though the explosion impacted the shield itself.

**Comment by JonnyNova** [comment]
Not observed in the pre-release version for 1.3-3326
