### ISSUE TITLE
Shields not working at all.

### ISSUE THREAD

**Issue by MusicManiac** [rimworld-frontierdevelopment/Shields#89]
Shields refuse to work at all. I believe it's because some mods incompatibility, but I don't know which one. In console it throws exception about references.

Log: https://gist.github.com/a7748a6d29b5d3ed21d2cdd184521fd5
Mods Config folder: [Config.zip](https://github.com/rimworld-frontierdevelopment/Shields/files/3558995/Config.zip)
Save: [Cadia Legion.zip](https://github.com/rimworld-frontierdevelopment/Shields/files/3558997/Cadia.Legion.zip)

**Comment by JonnyNova** [comment]
Is this still an issue?

A quick glance of the logs suggests that it might be related to turn it on or off but that isn't tested.

**Comment by JonnyNova** [comment]
From log:
```
Exception ticking Building_ShieldGenerator512138 (at (58, 0, 201)): System.NullReferenceException: Object reference not set to an instance of an object
at FrontierDevelopments.Shields.Buildings.Building_ElectricShield.Tick () <0x00065>
at (wrapper dynamic-method) Verse.TickList.Tick_Patch2 (object) <0x00497>
```

Probably has no `energySource`

https://github.com/rimworld-frontierdevelopment/Shields/blob/master/Source/Shields/Buildings/Building_ElectricShield.cs#L50

https://github.com/rimworld-frontierdevelopment/Shields/blob/master/Source/General/IEnergySource.cs#L17

TODO: Test turn it on or off

**Comment by JonnyNova** [comment]
Not turn it on or off or TD Enhancement related

**Comment by JonnyNova** [comment]
Energy source has been rewritten, likely invalid now.
