### ISSUE TITLE
Shields not working BUG

### ISSUE THREAD

**Issue by Miner28** [rimworld-frontierdevelopment/Shields#90]
When i place down shield it starts spamming error in console and shield doesn't work

Exception ticking Building_ShieldGeneratorLarge555704 (at (145, 0, 198)): System.NullReferenceException: Object reference not set to an instance of an object
  at FrontierDevelopments.Shields.Buildings.Building_ElectricShield.Tick () [0x00000] in <filename unknown>:0 
  at Verse.TickList.Tick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update_Patch1(Object)

**Comment by JonnyNova** [comment]
Can you share the full log?

**Comment by JonnyNova** [comment]
Duplicate of #90
